export const mockCollaborators = [
  {
    id: 1,
    uuid: "user-1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://i.pravatar.cc/150?img=1",
    permission: "edit",
    status: "accepted",
    accepted_at: "2024-03-20T10:00:00Z",
  },
  {
    id: 2,
    uuid: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
    permission: "read",
    status: "accepted",
    accepted_at: "2024-03-19T15:30:00Z",
  },
  {
    id: 3,
    uuid: "user-3",
    name: "Mike Johnson",
    email: "mike@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
    permission: "edit",
    status: "pending",
    accepted_at: null,
  },
];
