const notifications = [
  {
    id: 2,
    type: "activation-success",
    title: "Account Verified",
    message: "Your account has been successfully verified!",
    status: "success",
    timestamp: "2025-05-10",
  },
  {
    id: 3,
    type: "invitation-pending",
    direction: "outgoing",
    title: "Invitation Sent",
    message: "Invitation sent to Jane Doe to collaborate on 'Project Plan'.",
    status: "warning",
    timestamp: "2025-05-10",
  },
  {
    id: 4,
    type: "invitation-pending",
    direction: "incoming",
    title: "Collaboration Invitation",
    message: "John Smith invited you to collaborate on 'Research Notes'.",
    status: "warning",
    timestamp: "2025-05-10",
  },
  {
    id: 5,
    type: "invitation-success",
    title: "Invitation Accepted",
    message: "Jane Doe accepted your invitation to collaborate.",
    status: "success",
    timestamp: "2025-05-10",
  },
  {
    id: 6,
    type: "invitation-failed",
    title: "Invitation Rejected",
    message: "John Smith rejected your invitation to collaborate.",
    status: "error",
    timestamp: "2025-05-10",
  },
  {
    id: 7,
    type: "invitation-accept",
    title: "Invitation Accepted",
    message: "You accepted an invitation from Alice to collaborate.",
    status: "success",
    timestamp: "2025-05-10",
  },
  {
    id: 8,
    type: "invitation-decline",
    title: "Invitation Declined",
    message: "You declined an invitation from Bob to collaborate.",
    status: "error",
    timestamp: "2025-05-10",
  },
];

export default notifications;
